# Generated by Django 5.2.7 on 2025-10-20 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photos',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
