# Generated by Django 5.2.7 on 2025-10-15 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='size',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='photos',
            name='technique',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='photos',
            name='title',
            field=models.TextField(max_length=500),
        ),
    ]
