# Generated by Django 5.2.7 on 2025-10-20 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0004_categorie_photos_categorie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='price',
            field=models.DecimalField(decimal_places=10, max_digits=10),
        ),
    ]
