# Generated by Django 5.2.7 on 2025-10-20 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0006_alter_photos_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='price',
            field=models.DecimalField(decimal_places=3, max_digits=8),
        ),
    ]
